from typing import List, Optional, Union

from api_objects.base import ApiObject, EnrichObject, QueryObject, Subclass
from api_objects.company import SearchedCompany, EnrichedCompany

__all__ = ['SearchedContact', 'EnrichedContact']


class ContactSearchQuery(QueryObject):
	address: Optional[str] = None
	boardMember: Optional[str] = None
	companyDescription: Optional[str] = None
	companyId: Optional[str] = None
	companyName: Optional[str] = None
	companyPastOrPresent: Optional[str] = None
	companyRanking: Optional[str] = None
	companyStructureIncludedSubUnitTypes: Optional[str] = None
	companyTicker: Optional[List[str]] = None
	companyType: Optional[str] = None
	companyWebsite: Optional[str] = None
	contactAccuracyScoreMax: Optional[str] = None
	contactAccuracyScoreMin: Optional[str] = None
	continent: Optional[str] = None
	country: Optional[str] = None
	degree: Optional[str] = None
	department: Optional[str] = None
	emailAddress: Optional[str] = None
	employeeCount: Optional[str] = None
	employeeRangeMax: Optional[str] = None
	employeeRangeMin: Optional[str] = None
	excludedRegions: Optional[str] = None
	excludeJobTitle: Optional[str] = None
	excludeManagementLevel: Optional[str] = None
	excludePartialProfiles: Optional[bool] = None
	executivesOnly: Optional[bool] = None
	firstName: Optional[str] = None
	fullName: Optional[str] = None
	fundingAmountMax: Optional[int] = None
	fundingAmountMin: Optional[int] = None
	fundingEndDate: Optional[str] = None
	fundingStartDate: Optional[str] = None
	hasBeenNotified: Optional[str] = None
	hashedEmail: Optional[str] = None
	hashTagString: Optional[str] = None
	industryCodes: Optional[str] = None
	industryKeywords: Optional[str] = None
	jobFunction: Optional[str] = None
	jobTitle: Optional[str] = None
	lastName: Optional[str] = None
	lastUpdatedDateAfter: Optional[str] = None
	lastUpdatedInMonths: Optional[int] = None
	locationCompanyId: Optional[List[str]] = None
	locationSearchType: Optional[str] = None
	managementLevel: Optional[str] = None
	metroRegion: Optional[str] = None
	middleInitial: Optional[str] = None
	naicsCodes: Optional[str] = None
	oneYearEmployeeGrowthRateMax: Optional[str] = None
	oneYearEmployeeGrowthRateMin: Optional[str] = None
	page: Optional[int] = None
	parentId: Optional[str] = None
	personId: Optional[str] = None
	phone: Optional[List[str]] = None
	positionStartDateMax: Optional[str] = None
	positionStartDateMin: Optional[str] = None
	primaryIndustriesOnly: Optional[bool] = None
	requiredFields: Optional[str] = None
	revenue: Optional[str] = None
	revenueMax: Optional[int] = None
	revenueMin: Optional[int] = None
	rpp: Optional[int] = None
	school: Optional[str] = None
	sicCodes: Optional[str] = None
	sortBy: Optional[str] = None
	sortOrder: Optional[str] = None
	state: Optional[str] = None
	street: Optional[str] = None
	subUnitTypes: Optional[str] = None
	supplementalEmail: Optional[List[str]] = None
	techAttributeTagList: Optional[str] = None
	twoYearEmployeeGrowthRateMax: Optional[str] = None
	twoYearEmployeeGrowthRateMin: Optional[str] = None
	ultimateParentId: Optional[str] = None
	validDateAfter: Optional[str] = None
	zipCode: Optional[str] = None
	zipCodeRadiusMiles: Optional[str] = None
	zoominfoContactsMax: Optional[str] = None
	zoominfoContactsMin: Optional[str] = None


class ContactEnrichQuery(QueryObject):
	companyId: Optional[Union[int, str]] = None
	companyName: Optional[str] = None
	emailAddress: Optional[str] = None
	externalURL: Optional[str] = None
	firstName: Optional[str] = None
	fullName: Optional[str] = None
	hashedEmail: Optional[str] = None
	jobTitle: Optional[str] = None
	lastName: Optional[str] = None
	lastUpdatedDateAfter: Optional[str] = None
	personId: Optional[Union[int, str]] = None
	phone: Optional[str] = None
	validDateAfter: Optional[str] = None


class EnrichedContact(EnrichObject):
	_datetime_fields = ['lastUpdatedDate', 'noticeProvidedDate', 'positionStartDate', 'validDate']
	_enrich_match_input = 'matchPersonInput'
	_subclasses = [Subclass('company', EnrichedCompany)]
	
	city = None
	company = None
	companyCity = None
	companyContinent = None
	companyCountry = None
	companyDescriptionList = None
	companyDivision = None
	companyEmployeeCount = None
	companyEmployeeRange = None
	companyFax = None
	companyId = None
	companyIndustries = None
	companyLogo = None
	companyNaicsCodes = None
	companyName = None
	companyPhone = None
	companyPrimaryIndustry = None
	companyRanking = None
	companyRevenue = None
	companyRevenueNumeric = None
	companyRevenueRange = None
	companySicCodes = None
	companySocialMediaUrls = None
	companyState = None
	companyStreet = None
	companyTicker = None
	companyType = None
	companyWebsite = None
	companyZipCode = None
	contactAccuracyScore = None
	continent = None
	country = None
	directPhoneDoNotCall = None
	education = None
	email = None
	employmentHistory = None
	externalUrls = None
	firstName = None
	hasCanadianEmail = None
	hashedEmails = None
	id = None
	isDefunct = None
	jobFunction = None
	jobTitle = None
	lastName = None
	lastUpdatedDate = None
	locationCompanyId = None
	managementLevel = None
	metroArea = None
	middleName = None
	mobilePhoneDoNotCall = None
	noticeProvidedDate = None
	personHasMoved = None
	phone = None
	picture = None
	positionStartDate = None
	region = None
	salutation = None
	state = None
	street = None
	suffix = None
	validDate = None
	withinCalifornia = None
	withinCanada = None
	withinEu = None
	zipCode = None


class SearchedContact(ApiObject):
	_datetime_fields = ['fundingEndDate', 'fundingStartDate', 'lastUpdatedDateAfter', 'validDateAfter']
	_subclasses = [Subclass('company', SearchedCompany)]
	
	company = None
	contactAccuracyScore = None
	firstName = None
	hasCompanyCountry = None
	hasCompanyEmployeeCount = None
	hasCompanyIndustry = None
	hasCompanyPhone = None
	hasCompanyRevenue = None
	hasCompanyState = None
	hasCompanyStreet = None
	hasCompanyZipCode = None
	hasDirectPhone = None
	hasEmail = None
	hasMobilePhone = None
	hasSupplementalEmail = None
	jobTitle = None
	lastName = None
	lastUpdatedDate = None
	middleName = None
	personId = None
	validDate = None
